In [9]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

# Add src directory to system path so we can import local modules
sys.path.append(str(Path.cwd().parent / "src"))

from preprocessing.loader import (
    load_all,
    build_inventory,
)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [10]:
DATA_DIR = Path("../data/raw/bharatflux")
datasets = load_all(DATA_DIR)
print(f"Datasets found: {len(datasets)}")

Datasets found: 38

In [11]:
inventory = build_inventory(datasets)
inventory

,Dataset,Site,Year,File Type,Rows,Columns,Start DoY,End DoY,Coverage (%),Column Names,Path
0,BFT_2016_LE_ET_dmean,BFT,2016,combined,366,3,1.0,366.0,100.0,"Day, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\BFT\BFT_2016_LE_ET_dmea...
1,BFT_2017_LE_ET_dmean,BFT,2017,combined,365,3,1.0,365.0,100.0,"Day, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\BFT\BFT_2017_LE_ET_dmea...
2,BFT_2018_LE_ET_dmean,BFT,2018,combined,365,3,1.0,365.0,100.0,"Day, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\BFT\BFT_2018_LE_ET_dmea...
3,BIT_2016_LE_ET_dmean,BIT,2016,combined,366,3,1.0,366.0,100.0,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\BIT\BIT_2016_LE_ET_dmea...
4,BIT_2017_LE_ET_dmean,BIT,2017,combined,365,3,1.0,365.0,100.0,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\BIT\BIT_2017_LE_ET_dmea...
5,BKC_2014_ET_dmean,BKC,2014,ET_only,204,2,162.0,365.0,55.9,"Day, ET_daily_mean (mm d-1)",..\data\raw\bharatflux\BKC\BKC_2014_ET_dmean.csv
6,BKC_2014_LE_dmean,BKC,2014,LE_only,204,2,162.0,365.0,55.9,"Day, LE_daily_mean (W m-2)",..\data\raw\bharatflux\BKC\BKC_2014_LE_dmean.csv
7,BKC_2015_ET_dmean,BKC,2015,ET_only,365,2,1.0,365.0,100.0,"Day, ET_daily_mean (mm d-1)",..\data\raw\bharatflux\BKC\BKC_2015_ET_dmean.csv
8,BKC_2015_LE_dmean,BKC,2015,LE_only,365,2,1.0,365.0,100.0,"Day, LE_daily_mean (W m-2)",..\data\raw\bharatflux\BKC\BKC_2015_LE_dmean.csv
9,BKC_2016_ET_dmean,BKC,2016,ET_only,64,3,1.0,64.0,17.5,"Day, ET_daily_mean (mm d-1), ET_daily_sd (mm d-1)",..\data\raw\bharatflux\BKC\BKC_2016_ET_dmean.csv
10,BKC_2016_LE_dmean,BKC,2016,LE_only,64,3,1.0,64.0,17.5,"Day, H_daily_mean (W m-2), H_daily_sd (W m-2)",..\data\raw\bharatflux\BKC\BKC_2016_LE_dmean.csv
11,DIT_2016_LE_ET_dmean,DIT,2016,combined,366,3,1.0,366.0,100.0,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\DIT\DIT_2016_LE_ET_dmea...
12,DIT_2017_LE_ET_dmean,DIT,2017,combined,365,3,1.0,365.0,100.0,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\DIT\DIT_2017_LE_ET_dmea...
13,JIT_2016_ET_LE_dmean,JIT,2016,combined,194,3,173.0,366.0,53.0,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\JIT\JIT_2016_ET_LE_dmea...
14,JIT_2017_ET_LE_dmean,JIT,2017,combined,365,3,1.0,365.0,100.0,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\JIT\JIT_2017_ET_LE_dmea...
15,JIT_2018_ET_LE_dmean,JIT,2018,combined,284,3,1.0,284.0,77.8,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\JIT\JIT_2018_ET_LE_dmea...
16,KKM_2014_LE_ET_dmean,KKM,2014,combined,350,3,16.0,365.0,95.9,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\KKM\KKM_2014_LE_ET_dmea...
17,KKM_2015_LE_ET_dmean,KKM,2015,combined,365,3,1.0,365.0,100.0,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\KKM\KKM_2015_LE_ET_dmea...
18,KKM_2016_LE_ET_dmean,KKM,2016,combined,366,3,1.0,366.0,100.0,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\KKM\KKM_2016_LE_ET_dmea...
19,KNP_2016_ET_dmean,KNP,2016,ET_only,367,2,1.0,366.0,100.3,"DoY, ET",..\data\raw\bharatflux\KNP\KNP_2016_ET_dmean.csv
20,KNP_2016_LE_dmean,KNP,2016,LE_only,366,2,1.0,366.0,100.0,"DoY, LE_daily_mean (W m-2)",..\data\raw\bharatflux\KNP\KNP_2016_LE_dmean.csv
21,KNP_2017_ET_dmean,KNP,2017,ET_only,366,2,1.0,365.0,100.3,"DoY, ET",..\data\raw\bharatflux\KNP\KNP_2017_ET_dmean.csv
22,KNP_2017_LE_dmean,KNP,2017,LE_only,365,2,1.0,365.0,100.0,"DoY, LE_daily_mean (W m-2)",..\data\raw\bharatflux\KNP\KNP_2017_LE_dmean.csv
23,KNP_2018_ET_dmean,KNP,2018,ET_only,366,2,1.0,365.0,100.3,"DoY, ET",..\data\raw\bharatflux\KNP\KNP_2018_ET_dmean.csv
24,KNP_2018_LE_dmean,KNP,2018,LE_only,365,2,1.0,365.0,100.0,"DoY, LE_daily_mean (W m-2)",..\data\raw\bharatflux\KNP\KNP_2018_LE_dmean.csv
25,NIT_2016_ET_LE_dmean,NIT,2016,combined,193,3,174.0,366.0,52.7,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\NIT\NIT_2016_ET_LE_dmea...
26,NIT_2017_ET_LE_dmean,NIT,2017,combined,365,3,1.0,365.0,100.0,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\NIT\NIT_2017_ET_LE_dmea...
27,NIT_2018_ET_LE_dmean,NIT,2018,combined,313,3,1.0,313.0,85.8,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\NIT\NIT_2018_ET_LE_dmea...
28,PVM_2017_ET_dmean,PVM,2017,ET_only,92,2,274.0,365.0,25.2,"Day, ET_daily_mean (mm d-1)",..\data\raw\bharatflux\PVM\PVM_2017_ET_dmean.csv
29,PVM_2017_LE_dmean,PVM,2017,LE_only,93,2,274.0,365.0,25.5,"Day, LE",..\data\raw\bharatflux\PVM\PVM_2017_LE_dmean.csv
30,SFT_2014_LE_ET_dmean,SFT,2014,combined,365,3,1.0,365.0,100.0,"Day, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\SFT\SFT_2014_LE_ET_dmea...
31,SFT_2015_LE_ET_dmean,SFT,2015,combined,365,3,1.0,365.0,100.0,"Day, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\SFT\SFT_2015_LE_ET_dmea...
32,SFT_2016_LE_ET_dmean,SFT,2016,combined,91,3,1.0,91.0,24.9,"Day, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\SFT\SFT_2016_LE_ET_dmea...
33,SIT_2016_LE_ET_dmean,SIT,2016,combined,198,3,169.0,366.0,54.1,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\SIT\SIT_2016_LE_ET_dmea...
34,SIT_2017_LE_ET_dmean,SIT,2017,combined,365,3,1.0,365.0,100.0,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\SIT\SIT_2017_LE_ET_dmea...
35,SIT_2018_LE_ET_dmean,SIT,2018,combined,313,3,1.0,313.0,85.8,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\SIT\SIT_2018_LE_ET_dmea...
36,UIT_2016_LE_ET_dmean,UIT,2016,combined,366,3,1.0,366.0,100.0,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\UIT\UIT_2016_LE_ET_dmea...
37,UIT_2017_LE_ET_dmean,UIT,2017,combined,365,3,1.0,365.0,100.0,"DoY, LE_daily_mean (W m-2), ET_daily_mean (mm ...",..\data\raw\bharatflux\UIT\UIT_2017_LE_ET_dmea...

In [12]:
dataset = datasets["BFT_2016_LE_ET_dmean"]
dataset.info

DatasetInfo(site='BFT', year=2016, file_type='combined', path=WindowsPath('../data/raw/bharatflux/BFT/BFT_2016_LE_ET_dmean.csv'))

In [13]:
dataset.info.site

'BFT'

In [14]:
dataset.info.year

2016

In [15]:
dataset.info.file_type

'combined'

In [16]:
dataset.data.head()

   Day  LE_daily_mean (W m-2)  ET_daily_mean (mm d-1)
0    1             121.533229                4.666875
1    2             124.119004                4.766169
2    3             104.577071                4.015759
3    4             109.743590                4.214153
4    5             110.055843                4.226144